BaseURL: "https://cv.mattjh.sh"
theme: "terminalcv"
title: "Mattjh CV"

params:
  description: "Mattias Holmgren - Software Engineer (AI, Cloud, Go, Dev Platforms)"
  prompt: "you@cv"
  promptColor: green
  promptSimbols: " $"
  promptSimbolsColor: grey
  exitLocation: https://www.mattjh.sh
  hidesource: true
  greeting: |
    Welcome to my interactive CLI resume.

    Type `help` for commands.
    Hint: If you prefer traditional, type `view-pdf`.

  whois:
    name: "Mattias Holmgren"
    profession: "Software Engineer"
    location: "Kalmar, Sweden"
    email: "me@mattjh.sh"
    homelink: "https://mattjh.sh"
    description: |
      Full-stack software engineer building cloud-native applications and
      developer platforms with Python, TypeScript, React, and AWS/Kubernetes.
      Recently delivered an enterprise Backstage.io platform with GenAI
      integrations, adopted across engineering teams and streamlining
      onboarding and workflow automation. Alongside professional work, I build
      high-performance Go tools and AI/ETL pipelines, and I’m eager to bring
      that expertise into larger-scale backend and developer tooling roles.

  social:
    - name: "github"
      url: "https://github.com/mattjh1"
    - name: "linkedIn"
      url: "https://www.linkedin.com/in/mattias-holmgren-b2407714a/"

  work:
    - jobTitle: Software Engineer | Solution Consultant
      color: red
      company: "tietoevry"
      location: Kalmar
      date: Aug 2022 – Present
      description: |
        • Designed and deployed an AI-enabled developer platform on Backstage.io,
          achieving 1,000+ daily active users and 100% month-over-month
          growth (11,000 monthly visits), improving onboarding time from weeks to days.
        • Built custom plugins for AI service discovery, governance/compliance,
          and feedback collection using Node.js/TypeScript; increased self-service
          adoption across engineering teams.
        • Integrated GenAI workflows into enterprise apps, reducing manual support
          lookups and speeding up resolution times.
        • Scaled AWS/Kubernetes microservices for high-volume workloads; also
          implemented serverless automation in Go for specific tasks.
        • Optimized CI/CD pipelines (GitHub Actions, GitLab CI), cutting build and
          deployment times by more than half.
        • Collaborated directly with enterprise clients to deliver tailored
          cloud-native solutions using Agile practices.

    - jobTitle: Web Administrator
      color: purple
      company: "Botkyrka Kommun"
      location: Stockholm
      date: Aug 2018 – Oct 2019
      description: |
        • Managed CMS for SiteVision platform in collaboration with external
          partners.
        • Gained early experience in agile practices, stakeholder management,
          and iterative delivery.

  education:
    - courseName: BSc Computer Science, Software Engineering
      color: red
      date: Jun 2018 – Jul 2021
      description: |
        Scholarship-awarded thesis. Strong foundation in software engineering
        principles, algorithms, and system design.

  skills:
    - name: Core Backend
      color: green
      description: |
        Python (FastAPI, Flask), Java (Spring Boot), TypeScript/Node.js
        (NestJS, Express.js), Go (personal projects + serverless functions).
        REST/GraphQL APIs, microservices, system design.

    - name: AI & GenAI
      color: green
      description: |
        RAG systems, LangChain, LLM integration, prompt engineering, GenAI
        workflow automation, hybrid search solutions.

    - name: Cloud & DevOps
      color: green
      description: |
        AWS (ECS, Lambda, IoT Core, SageMaker), Kubernetes, Docker, CI/CD
        pipelines, GitHub Actions, GitLab CI, infrastructure as code.

    - name: Developer Platforms
      color: green
      description: |
        Backstage.io plugin development (AI integration, subscription mgmt,
        governance/compliance), workflow standardization, developer experience.

    - name: Databases
      color: orange
      description: |
        PostgreSQL, MongoDB, Redis, Neo4j. Schema design, query optimization,
        integration with microservices.

  softskills:
    - name: Problem Solving
      color: green
      description: Pragmatic solutions to complex challenges with focus on scalability.
    - name: Collaboration
      color: green
      description: Effective in cross-functional teams, Agile/SCRUM experience.
    - name: Adaptability
      color: green
      description: Active learner, exploring AI/ML and emerging dev tools.

  languages:
    - name: Swedish
      color: green
      description: Native
    - name: English
      color: green
      description: Professional fluency

  projects:
    - title: AI-Powered Developer Platform
      color: red
      date: 2024 –
      description: |
        Enterprise Backstage.io platform with AI integrations and custom plugins,
        scaling to 1,000+ daily active developers with 100% month-over-month growth.
        Improved developer workflows with GenAI-enhanced automation across
        multiple engineering teams.

    - title: gRAG Pipeline
      color: red
      date: 2024 –
      link: https://github.com/mattjh1/gRAG
      description: |
        ETL + RAG pipeline using FastAPI and Neo4j. Hybrid search (vector +
        structured queries) and Chainlit chat interface.

    - title: goETL
      color: red
      date: 2024 –
      link: https://github.com/mattjh1/goetl
      description: |
        High-performance ETL pipeline in Go. Concurrent data processing,
        embedding model integration, multi-database support.

    - title: PSI-Map
      color: red
      date: 2025 –
      link: https://github.com/mattjh1/psi-map
      description: |
        CLI tool for batch PageSpeed Insights analysis in Go. Features caching,
        concurrent processing, multi-format output, CI/CD automation.

  certifications:
    - certName: KCNA — Kubernetes and Cloud Native Associate
      color: green
      company: Linux Foundation
      date: Jan 2025
      badge: https://www.credly.com/badges/5e030c4c-4f9f-432f-9754-b92b842eda0c
      description: |
        Validates knowledge of Kubernetes, container orchestration, cloud-native
        networking, security principles, and CNCF ecosystem.
