BaseURL: "https://cv.mattjh.sh"
theme: "terminalcv"
title: "Mattjh CV"

params:
  description: "mattjh cv - terminal format"
  prompt: "you@cv"
  promptColor: green
  promptSimbols: " $"
  promptSimbolsColor: grey
  # startxLocation: https://www.mattjh.sh
  # hideSocialName: true
  exitLocation: https://www.mattjh.sh
  hidesource: true
  greeting: |

    Welcome to my interactive CLI resume

    Type `help` for a list of available commands
    Hint: Does the terminal scare you? Type `view-pdf` and pretend this never happened.
  whois:
    name: "Mattias Holmgren"
    profession: "Software Engineer"
    location: "Kalmar, Sweden"
    email: "me@mattjh.sh"
    homelink: "https://mattjh.sh"
    description: |
      Passionate software engineer with a focus on backend development, AI/GenAI applications, and developer tooling. 
      Experienced in Python, Java, Node.js, and TypeScript, with practical knowledge of modern frontend frameworks. 
      Proven track record delivering scalable solutions using cloud infrastructure (AWS), Kubernetes, and CI/CD pipelines.
      Recent focus on Backstage.io plugin development, GenAI integrations, and building developer experience tools at enterprise scale.
      Comfortable working across the full stack and tackling complex problems with pragmatic, well-tested solutions.

  social:
    - name: "github"
      url: "https://github.com/mattjh1"
    - name: "linkedIn"
      url: "https://www.linkedin.com/in/mattias-holmgren-b2407714a/"

  work:
    - jobTitle: Solution Consultant
      color: red
      company: "tietoevry"
      location: Kalmar
      date: August 2022 - Present
      description: |
        Developed AI-driven and cloud-native solutions, working directly with clients to deliver 
        tailored applications. Recent focus includes building developer platforms on Backstage.io with AI marketplace 
        integrations, custom plugin development, and GenAI workflow enhancements. Managing full-stack development, 
        AWS infrastructure, and Kubernetes deployments across diverse project portfolios.

    - jobTitle: Web administrator
      color: purple
      company: "Botkyrka Kommun"
      location: Stockholm
      date: August 2018  - October 2019
      description: |
        Managed CMS for SiteVision platform while collaborating with external consulting partners 
        to implement agile methodologies. Gained foundational experience in stakeholder management 
        and iterative development processes.

  education:
    - courseName: BSc Computer Science, Software Engineering
      color: red
      date: June 2018 - July 2021
      description: |
        Completed BSc program in Computer Science with Software Engineering focus. 
        Received scholarship for outstanding thesis performance, demonstrating strong 
        academic foundation in software development principles and practices.

  skills:
    - name: Python
      color: green
      percentage: 90
      description: |
        Strong Python development skills across web applications, AI/ML integrations, and automation tools. 
        Experience with FastAPI, data processing, and AI model training. Applied in RAG systems, 
        ETL pipelines, and various utility applications.

    - name: TypeScript/Node.js
      color: green
      percentage: 85
      description: |
        Proficient in Node.js and TypeScript for backend and frontend development. 
        Hands-on experience with NestJS, React (Next.js), and Backstage.io plugin development. 
        Built scalable applications using modern JavaScript frameworks and tools.

    - name: Backstage.io
      color: green
      percentage: 85
      description: |
        Extensive experience developing custom Backstage plugins including AI marketplace integration, 
        subscription management, and developer feedback systems. Built plugin templates for workflow 
        standardization and contributed to enterprise-scale developer platform implementations.

    - name: AI/GenAI Integration
      color: green
      percentage: 80
      description: |
        Practical experience integrating GenAI capabilities into developer workflows and business applications. 
        Built RAG systems using LangChain, implemented hybrid search solutions, and developed AI-powered 
        developer tools. Experience with various LLM implementations and prompt engineering techniques.

    - name: AWS Services
      color: green
      percentage: 80
      description: |
        Solid AWS experience across core services including S3, Lambda, ECS/ECR, IoT Core, and SageMaker. 
        Implemented CI/CD pipelines, managed container orchestration, and deployed scalable cloud solutions 
        for production environments.

    - name: Bash
      color: green
      percentage: 85
      description: |
        Strong scripting abilities for automation, deployment, and system administration tasks. 
        Daily use for productivity enhancement and process optimization in development workflows.

    - name: Go
      color: orange
      percentage: 75
      description: |
        Growing proficiency in Go for CLI tools, AWS Lambdas, and system-level applications. 
        Appreciate the language's simplicity and performance characteristics. 
        Recent projects include ETL pipelines and performance monitoring tools.

    - name: Neo4j
      color: orange
      percentage: 70
      description: |
        Experience with graph database modeling and complex query optimization. 
        Integrated Neo4j into RAG systems and knowledge graph applications, 
        including backup/restore implementations and hybrid search capabilities.

    - name: Java
      color: orange
      percentage: 70
      description: |
        Solid foundation in Java with experience in Spring Boot and Quarkus frameworks. 
        Applied in enterprise backend development and microservices architectures.

  softskills:
    - name: Problem Solving
      percentage: 85
      color: green
      description: |
        Enjoy tackling complex technical challenges and finding pragmatic solutions. 
        Focus on understanding root causes and implementing maintainable fixes that scale.

    - name: Team Collaboration
      percentage: 80
      color: green
      description: |
        Work effectively with cross-functional teams, from engineers to product managers. 
        Value clear communication and alignment while contributing to shared technical decisions.

    - name: Continuous Learning
      percentage: 90
      color: green
      description: |
        Actively explore new technologies and methodologies. Stay current with industry trends, 
        particularly in AI/ML space and developer tooling ecosystem.

  languages:
    - name: Swedish
      color: green
      percentage: 100
      description: Native speaker

    - name: English
      color: green
      percentage: 100
      description: Professional proficiency

  projects:
    - title: AI-Powered Developer Platform for Global Telecom
      color: red
      date: Since 2024
      description: |
        Built AI marketplace integration within Backstage.io platform serving thousands of developers. 
        Developed custom plugins including subscription management, developer feedback collection, AI service discovery,
        and AI governance/compliance systems. Implemented plugin templates for workflow standardization and integrated 
        GenAI capabilities into developer workflows using TypeScript, Node.js, and modern web technologies.

    - title: gRAG Pipeline and RAG Application
      color: red
      date: Since 2024
      link: https://github.com/mattjh1/gRAG
      description: |
        Advanced ETL pipeline with RAG system integration. Processes text-based formats and stores 
        data as knowledge graph in Neo4j. Features hybrid search combining vector embeddings with 
        structured queries, FastAPI interface, and Chainlit chat application for interactive querying.

    - title: goETL Pipeline
      color: red
      date: Since 2024
      link: https://github.com/mattjh1/goetl
      description: |
        High-performance ETL pipeline written in Go for RAG solutions. Supports chunked text processing, 
        embedding model integration, and multiple database backends (Redis, PostgreSQL). 
        Designed for concurrent data handling and scalable RAG system implementations.

    - title: PSI-Map - PageSpeed Insights Analyzer
      color: red
      date: Since 2025
      link: https://github.com/mattjh1/psi-map
      description: |
        Command-line tool for batch PageSpeed Insights analysis using sitemap.xml files. 
        Built in Go with concurrent processing, intelligent caching, multiple output formats, 
        and comprehensive CI/CD pipeline with automated builds and cross-platform releases.

    - title: AI Developer Tool
      color: red
      date: Since 2024
      description: |
        Collaborated with a diverse team to develop AI-powered developer tools, 
        focusing on a robust RAG (Retrieval-Augmented Generation) application. Integrated ETL processes, 
        multiple data sources, and hybrid search using Elasticsearch for efficient retrieval. 
        Fine-tuned models for complex queries, ensuring scalability and low-latency execution.

    - title: Resource Supply System
      color: red
      date: Since 2022
      description: |
        Streamlined workflow system for electrical components reseller using AngularJS, Neo4j, 
        and AWS stack. Includes CI/CD pipelines, Lambda functions, IoT Core, and SageMaker integrations.

    - title: RAG + GenAI Proof of Concept
      color: red
      date: Since 2022
      description: |
        Q/A solution integrating large documentation datasets using LangChain for prompt engineering, 
        FAISS for similarity search, and Chainlit for frontend interface. Demonstrated effective 
        GenAI application in enterprise knowledge management.

    - title: IoT Sensor Application
      color: red
      date: Since 2022
      description: |
        Team collaboration on fullstack IoT application for beekeepers to monitor connected beehives. 
        AWS-hosted solution with advanced IoT features and real-time monitoring capabilities.

    - title: Dotfiles Setup
      color: red
      date: Since 2023
      link: https://github.com/mattjh1/dotfiles
      description: |
        Automated development environment setup using Ansible, chezmoi, and Go templates. 
        Supports macOS and Linux with 1Password integration for secure credential management. 
        Single-command environment recreation for rapid system adaptation.

  certifications:
    - certName: KCNA Kubernetes and Cloud Native Associate
      color: green
      company: The Linux Foundation
      date: January 31, 2025
      badge: https://www.credly.com/badges/5e030c4c-4f9f-432f-9754-b92b842eda0c
      description: |
        Foundational knowledge of Kubernetes and cloud-native technologies, including container orchestration, 
        networking, security principles, and CNCF ecosystem understanding. Validates practical skills 
        in application deployment and cluster architecture.
