## Example Config file
BaseURL: "https://example.com"
theme: "terminalcv"
title: "Mattjh CV"

params:
  description: "mattjh cv terminal format"
  prompt: "recruiter@cv"
  promptColor: green
  promptSimbols: ":~"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # hideSocialName: true
  # exitLocation: 'about:blank'
  hidesource: true
  greeting: |
    Welcome to my online resume


    Type 'help' for a list of available commands

  whois:
    name: "Mattias Holmgren"
    profession: "Software Engineer"
    location: "Kalmar, Sweden"
    email: "me@mattjh.sh"
    # homelink: "https://myHomePage.com"
    description: |
      Passionate, driven, and curious software engineer with a love for backend development,
      AI, and a recent deep dive into prompt engineering. I thrive on learning new technologies
      and methodologies to stay at the forefront of the ever-evolving tech landscape. 
      Proficient in Python, Java, Node.js, and experienced with common frontend frameworks. 
      Additionally, I have a solid understanding of Go and am well-versed in Git for effective source control. 
      My commitment to continuous learning fuels my enthusiasm for tackling complex challenges and delivering innovative solutions.
      I bring a well-rounded AWS knowledge, having successfully utilized it in the majority of my professional projects, 
      ensuring robust, scalable, and secure solutions.
      I possess a comprehensive knowledge of databases, spanning SQL, NoSQL, and GraphQL technologies. 
      I have hands-on experience with database design, optimization, and management, ensuring efficient and scalable data solutions.

  social:
    ## IF you want to keep them aligned just add spaces
    - name: "github"
      url: "  https://github.com/mattjh1"
    - name: "linkedIn"
      url: "  https://www.linkedin.com/in/mattias-holmgren-b2407714a/"

  work:
    - jobTitle: Software developer
      color: red
      company: "tietoevry"
      location: Kalmar
      date: August 2022 - Present
      description: My first job as a software engineer after completed studies

    - jobTitle: Web administrator
      color: purple
      company: "Botkyrka Kommun"
      location: Stockholm
      date: July 2016  - July 2019
      description: |
        i worked as a CMS admin for a SiteVision site, it was
        at this job i learned about agile methodologies and working closely
        with external consulting partners.

  education:
    - courseName: BSc Computer Science, Software Engineering
      color: red
      date: June 2018 - July 2021
      description: |
        Completed a rigorous BSc program in Computer Science with a focus on Software Engineering. 
        Demonstrated a commitment to excellence, receiving a prestigious scholarship for outstanding performance on my thesis.

  skills:
    - name: Python
      color: green
      percentage: 90
      description: |
        Adept in Python programming, I've applied the language to develop a variety of utility scripts and demonstrate its versatility in various projects. 
        Experienced in training AI models and working with notebooks, my Python proficiency extends across diverse applications, 
        showcasing its adaptability and power.

    - name: Java
      color: green
      percentage: 90
      description: |
        Proficient in Java, with a solid foundation in the core language and extensive experience 
        with popular frameworks including Quarkus and Spring Boot. 
        Well-versed in leveraging Java to develop robust and scalable backend solutions.

    - name: Bash
      color: green
      percentage: 85
      description: |
        Proficient in Bash scripting, I leverage this skill extensively in my day-to-day work to enhance productivity.
        From automating repetitive tasks to crafting efficient and effective solutions, my expertise in Bash scripting contributes
        to streamlined workflows and optimized processes.

    - name: AWS Services
      color: green
      percentage: 80
      description: |
        Proficient in AWS Services, I've demonstrated expertise in a wide range of cloud technologies. 
        From managing data with S3 to serverless architecture using Lambda, and extending to CI/CD pipelines, 
        container orchestration with ECR/ECS, IoT solutions with IoT Core, and leveraging SageMaker for machine learning projects. 
        My hands-on experience across these services reflects a robust understanding of cloud infrastructure and a proven ability to design 
        and implement scalable solutions on the AWS platform.

    - name: Node.js
      color: orange
      percentage: 70
      description: |
        Proficient in Node.js with hands-on experience in NestJS, Angular, React (Next.js), and utilizing the Prisma ORM. 
        My expertise in Node.js extends to building scalable and efficient server-side applications and leveraging modern frameworks 
        for dynamic and responsive web development.

    - name: Prompt Engineering
      color: orange
      percentage: 70
      description: |
        Experienced in Prompt Engineering, I've conducted experiments with various Language Model (LLMs) implementations. 
        Utilizing the LangChain framework, I crafted a Proof of Concept (POC) integrating RAG (Retrieval-Augmented Generation) and generalized AI. 
        Navigating the dynamic landscape of vector databases, I've gained valuable insights into the evolving field, 
        contributing to my adaptability and innovation in this fast-paced domain.

    - name: Go lang
      color: orange
      percentage: 65
      description: |
        Possessing a growing proficiency in Go lang, I've utilized the language to create command-line interfaces (CLI) and AWS Lambdas. 
        I am drawn to the language for its simplicity, efficiency, and concurrency model. 
        Eager to further enhance my Go expertise and actively seeking opportunities to contribute my skills in professional projects.

    - name: Neo4j
      color: orange
      percentage: 70

  softskills:
    - name: Effective Communication
      percentage: 80
      color: green
      description: |
        Known for clear and concise communication, I excel in conveying complex ideas with simplicity. 
        A soft-spoken and gentle communicator, I foster collaboration and ensure that ideas are understood by diverse audiences.

    - name: Active Listening
      percentage: 90
      color: green
      description: |
        Adept at active listening, I prioritize understanding others' perspectives and needs.
        While not the most talkative, my attentive and thoughtful communication style contributes to effective teamwork and problem-solving.

  languages:
    - name: Swedish
      color: green
      percentage: 100
      description: Mother's tongue

    - name: English
      color: green
      percentage: 100
      description: Professional level

  projects:
    - title: IoT sensor application
      color: red
      date: since 2022
      link: https://app.beelab.se
      description: |
        Worked in a team of dedicated developers to create a fullstack application hosted on AWS
        for beekeepers to monitor connected beehives with advanced IoT features.

    - title: Resource supply system
      color: red
      date: since 2022
      #link: -
      description: |
        The goal of this project was to create a system for a electrical components reseller that
        create value for the client by streamlining the workflow of buyers and sellers internally.
        The project is a big success, and ongoing. Technologies include AngularJS, Neo4j, AWS stack
        with CI/CD, Lambda functions, IoT Core and sagemaker.

    - title: RAG + gen AI
      color: red
      date: Since 2022
      description: |
        Spearheaded the development of a comprehensive Proof of Concept (POC) to establish an effective QA solution. 
        The project involved the integration of a large dataset of documentation,
        leveraging cutting-edge technologies such as LangChain for prompt engineering, FAISS for efficient similarity search, 
        and chainlit for clean and effortless frontend application.

    - title: AI Developer tool
      color: red
      date: 2024
      description: |
        I collaborated with a diverse team of experts to develop cutting-edge developer tools powered by generative AI. 
        Our primary achievement was building a robust RAG (Retrieval-Augmented Generation) application, integrating ETL processes, multiple data sources, code repositories, documentation, and general files, with a hybrid search capability. 
        The solution is highly flexible, designed to seamlessly integrate into any codebase. 
        Additionally, we fine-tuned smaller models to handle complex, multi-part RAG queries, ensuring the system could adapt to intricate user needs.

    - title: goetl pipeline
      color: red
      date: 2024
      link: https://github.com/mattjh1/goetl
      description: |
        as a personal project, i developed goetl, a highly performant etl pipeline written in go, designed to extract, transform, and load data for rag (retrieval-augmented generation) solutions.
        the tool specializes in processing data from arbitrary file types using flexible configuration options, and leverages go's goroutines to ensure efficient, concurrent data handling.
        goetl provides core functionality such as chunked text splitting, seamless integration with embedding models, and support for multiple database types including redis and postgresql.
        its configurable and scalable nature makes it adaptable to a wide range of file sources and enables hybrid search capabilities in rag systems.

  # certifications:
  #   - certName: Example Cert
  #     company: Example Certifying Company
  #     date: Date of Completion
  #     #description: Lorem Ipsum

  # misc:
  #   #commandName: newcommand
  #   title: "This Section can have a different command name"
  #   titleColor: teal
  #   content: |
  #     Here the title and the content can have different colors
  #     The content can be multi

  #     line

  #     And spaces       will be respected as well
  #     This section will have the default command: misc
  #     but you can name it something else with the property
  #     commandName: <String>
  #     Give it a shot and try and uncomment the line
  #     commandName: newcommand
  #     now instead of misc you can execute the newcommand for this section
  #     Auto completion will know it too! :D

  #   contentColor: orange
