BaseURL: "https://cv.mattjh.sh"
theme: "terminalcv"
title: "Mattjh CV"

params:
  description: "mattjh cv - terminal format"
  prompt: "you@cv"
  promptColor: green
  promptSimbols: ":~"
  # promptSimbolsColor: grey
  # startxLocation: https://www.mattjh.sh
  # hideSocialName: true
  exitLocation: https://www.mattjh.sh
  hidesource: true
  greeting: |

    ###################################################################################
    #                                   ______________________________                #
    #                                  < Keep it simple. Keep it Unix. >              #
    #                                   ------------------------------                #
    #                                                   \         ,        ,          #
    #                                                    \       /(        )`         #
    #                                                     \      \ \___   / |         #
    #                                                      \     /- _  `-/  '         #
    #   __  __       _   _   _ _                                (/\/ \ \   /\         #
    #  |  \/  |     | | | | (_) |                               / /   | `    \        #
    #  | \  / | __ _| |_| |_ _| |__     _____   __              O O   ) /    |        #
    #  | |\/| |/ _` | __| __| | '_ \   / __\ \ / /              `-^--'`<     '        #
    #  | |  | | (_| | |_| |_| | | | | | (__ \ V /              (_.)  _  )   /         #
    #  |_|  |_|\__,_|\__|\__| |_| |_|  \___| \_/                `.___/`    /          #
    #                      _/ |                                   `-----' /           #
    #                     |__/                       <----.     __ / __   \           #
    #                                                <----|====O)))==) \) /====       #
    #                                                <----'    `--' `.__,' \          #
    #                                                             |        |          #
    #                                                              \       /          #
    #                                                         ______( (_  / \_____    #
    #                                                      ,'  ,-----'   |        \   #
    #                                                      `--{__________)        \/  #
    #                                                                                 #
    ###################################################################################

    Welcome to my online resume


    Type 'help' for a list of available commands
  whois:
    name: "Mattias Holmgren"
    profession: "Software Engineer"
    location: "Kalmar, Sweden"
    email: "me@mattjh.sh"
    homelink: "https://mattjh.sh"
    description: |
      Passionate, driven, and curious software engineer with a love for linux, backend development,
      AI, with a recent deep dive into GenAI and prompt engineering. I thrive on learning new technologies and methodologies. 
      Proficient in Python, Java, Node.js, and experienced with common frontend frameworks. 
      Additionally, I have a solid understanding of Go and am well-versed in Git for effective source control. 
      My commitment to continuous learning fuels my enthusiasm for tackling complex challenges and delivering innovative solutions.
      I bring a well-rounded AWS knowledge, having successfully utilized it in the majority of my professional projects, 
      ensuring robust, scalable, and secure solutions.
      I possess a comprehensive knowledge of databases, spanning SQL, NoSQL, and GraphQL technologies.

  social:
    ## IF you want to keep them aligned just add spaces
    - name: "github"
      url: "https://github.com/mattjh1"
    - name: "linkedIn"
      url: "https://www.linkedin.com/in/mattias-holmgren-b2407714a/"

  work:
    - jobTitle: Software developer
      color: red
      company: "tietoevry"
      location: Kalmar
      date: August 2022 - Present
      description: |
        Working in a diverse set of projects, ranging from full-stack application, developing AI applications, managing, and deploying 
        cloud infrastructure on AWS and kubernetes.

    - jobTitle: Web administrator
      color: purple
      company: "Botkyrka Kommun"
      location: Stockholm
      date: July 2016  - July 2019
      description: |
        i worked as a CMS admin for a SiteVision site, it was
        at this job i learned about agile methodologies and working closely
        with external consulting partners.

  education:
    - courseName: BSc Computer Science, Software Engineering
      color: red
      date: June 2018 - July 2021
      description: |
        Completed a rigorous BSc program in Computer Science with a focus on Software Engineering. 
        Demonstrated a commitment to excellence, receiving a prestigious scholarship for outstanding performance on my thesis.

  skills:
    - name: Python
      color: green
      percentage: 90
      description: |
        Adept in Python programming, I've applied the language to develop a variety of utility scripts and demonstrate its versatility in various projects. 
        Experienced in training AI models and working with notebooks, my Python proficiency extends across diverse applications, 
        showcasing its adaptability and power.

    - name: Bash
      color: green
      percentage: 85
      description: |
        Proficient in Bash scripting, I leverage this skill extensively in my day-to-day work to enhance productivity.
        From automating repetitive tasks to crafting efficient and effective solutions, my expertise in Bash scripting contributes
        to streamlined workflows and optimized processes.

    - name: Node.js
      color: green
      percentage: 85
      description: |
        Proficient in Node.js with hands-on experience in NestJS, Angular, React (Next.js), and utilizing the Prisma ORM. 
        My expertise in Node.js extends to building scalable and efficient server-side applications and leveraging modern frameworks 
        for dynamic and responsive web development.

    - name: Prompt Engineering
      color: green
      percentage: 85
      description: |
        Experienced in Prompt Engineering, I've conducted experiments with various Language Model (LLMs) implementations. 
        Utilizing the LangChain framework, I crafted a Proof of Concept (POC) integrating RAG (Retrieval-Augmented Generation) and generalized AI. 
        Navigating the dynamic landscape of vector databases, I've gained valuable insights into the evolving field, 
        contributing to my adaptability and innovation in this fast-paced domain.

    - name: AWS Services
      color: green
      percentage: 80
      description: |
        Proficient in AWS Services, I've demonstrated expertise in a wide range of cloud technologies. 
        From managing data with S3 to serverless architecture using Lambda, and extending to CI/CD pipelines, 
        container orchestration with ECR/ECS, IoT solutions with IoT Core, and leveraging SageMaker for machine learning projects. 
        My hands-on experience across these services reflects a robust understanding of cloud infrastructure and a proven ability to design 
        and implement scalable solutions on the AWS platform.

    - name: Neo4j
      color: orange
      percentage: 70
      description: |
        I have utilized Neo4j in several projects, leveraging its graph database capabilities for complex data modeling and querying.
        My experience includes designing and managing knowledge graphs, optimizing queries, and integrating Neo4j with other tools like Langchain and FastAPI.
        One key project is gRAG, which integrates Neo4j into a sophisticated ETL pipeline and RAG application.
        The pipeline processes and stores data in Neo4j for hybrid search, combining vector embeddings with Cypher queries for enhanced information retrieval. 
        Additionally, I implemented database backup, restore features, and interactive querying through a Chainlit chat interface.

    - name: Java
      color: orange
      percentage: 70
      description: |
        Proficient in Java, with a solid foundation in the core language and experience 
        with popular frameworks including Quarkus and Spring Boot. 
        Well-versed in leveraging Java to develop robust and scalable backend solutions.

    - name: Go lang
      color: orange
      percentage: 65
      description: |
        Possessing a growing proficiency in Go lang, I've utilized the language to create command-line interfaces (CLI) and AWS Lambdas. 
        I am drawn to the language for its simplicity, efficiency, and concurrency model. 
        Eager to further enhance my Go expertise and actively seeking opportunities to contribute my skills in professional projects.

    - name: Ansible
      color: orange
      percentage: 60
      description: |
        My interest in automation led me to Ansible, where I've started using it to streamline setups and configurations.
        Though my experience is mainly with personal projects, I’m learning quickly and appreciate its agentless, idempotent design for efficient, repeatable tasks.
        I plan to expand my Ansible use into larger, more complex environments.

  softskills:
    - name: Effective Communication
      percentage: 75
      color: green
      description: |
        Continuously developing my communication skills to better articulate ideas and contribute effectively in team settings.
        I value clarity and aim to present information in a straightforward manner while ensuring that all stakeholders stay informed.

    - name: Active Listening
      percentage: 75
      color: green
      description: |
        Dedicated to honing my active listening skills to understand others' viewpoints and foster collaborative discussions.
        I am committed to becoming more attentive and responsive to input, ensuring productive interactions within the team.

  languages:
    - name: Swedish
      color: green
      percentage: 100
      description: Mother's tongue

    - name: English
      color: green
      percentage: 100
      description: Professional level

  projects:
    - title: IoT sensor application
      color: red
      date: since 2022
      link: https://app.beelab.se
      description: |
        Worked in a team of dedicated developers to create a fullstack application hosted on AWS
        for beekeepers to monitor connected beehives with advanced IoT features.

    - title: Resource supply system
      color: red
      date: since 2022
      #link: -
      description: |
        The goal of this project was to create a system for a electrical components reseller that
        create value for the client by streamlining the workflow of buyers and sellers internally.
        The project is a big success, and ongoing. Technologies include AngularJS, Neo4j, AWS stack
        with CI/CD, Lambda functions, IoT Core and sagemaker.

    - title: RAG + gen AI
      color: red
      date: Since 2022
      description: |
        Spearheaded the development of a Proof of Concept (POC) to establish an effective Q/A solution. 
        The project involved the integration of a large dataset of documentation,
        leveraging cutting-edge technologies such as LangChain for prompt engineering, FAISS for efficient similarity search, 
        and chainlit for clean and effortless frontend application.

    - title: Trello Board CSV Exporter
      color: red
      date: Since 2023
      link: https://github.com/mattjh1/trello-csv-exporter
      description: |
        I developed a Python-based tool to export Trello board data into CSV format, allowing users to manage and analyze their Trello data efficiently.
        The script interacts with the Trello API, and provides flexible configuration options, including output to local directories or S3, with optional AWS profile integration.
        The project is designed for ease of use with `.env`-based API key management and supports environment isolation through virtual environments.
        It features customizable command-line arguments and streamlines the process of exporting Trello data into an organized format for further analysis.

    - title: dotfiles setup
      color: red
      date: Since 2023
      link: https://github.com/mattjh1/dotfiles
      description: |
        I created a robust and portable dotfiles setup, using a combination of `ansible`, `chezmoi`, and `Go templates` to manage and deploy development environments across multiple machines seamlessly.
        This setup automates the installation of essential tools like `zsh`, `nvim`, `tmux`, `git`, and others, while leveraging `1password` integration for secure credential management.
        With templates to handle host-specific differences, the environment is highly flexible and supports both macOS and Linux configurations.
        A single command can recreate my full development environment, ensuring that I can quickly adapt to any system with minimal manual setup.

    - title: AI Developer Tool
      color: red
      date: Since 2024
      description: |
        I collaborated with a diverse team of experts to develop cutting-edge developer tools powered by generative AI. 
        Our primary achievement was building a robust RAG (Retrieval-Augmented Generation) application, integrating ETL processes, multiple data sources, code repositories, documentation, and general files, with a hybrid search capability. 
        The solution leveraged the Elasticsearch stack for efficient indexing, retrieval, and ranking, optimizing search performance across structured and unstructured data.  
        Additionally, we fine-tuned smaller models to handle complex, multi-part RAG queries, ensuring the system could adapt to intricate user needs.  
        The project emphasized scalability, enabling seamless integration into any codebase while maintaining low-latency query execution.

    - title: gRAG pipeline and RAG application
      color: red
      date: Since 2024
      link: https://github.com/mattjh1/gRAG
      description: |
        gRAG is a multi-faceted project that integrates an advanced ETL pipeline with a Retrieval-Augmented Generation (RAG) system. 
        The ETL pipeline processes various text-based file formats, extracts and transforms data using semantic splitting and LLM-based document parsing, and stores it as a knowledge graph in Neo4j. 
        This enables hybrid search capabilities that combine vector embeddings and structured queries for enhanced information retrieval.

        The RAG application utilizes both hybrid and structured retrievers. The hybrid retriever searches vector embeddings for cosine similarity, while the structured retriever extracts entities from queries and executes Neo4j Cypher queries for relevant nodes and relationships, enhancing results for complex RAG tasks.

        Additionally, the project includes a backup and restore feature for Neo4j databases. For demonstration, a pre-built knowledge graph based on Bram Stoker's *Dracula* is included, which can be restored using an automated script or manual commands for quick setup. The database is powered by Langchain's experimental LLMGraphTransformer to generate graph structures from literature.

        The project also features a FastAPI-based interface and integrates with a Chainlit chat application for interactive querying and testing.

    - title: goetl pipeline
      color: red
      date: Since 2024
      link: https://github.com/mattjh1/goetl
      description: |
        as a personal project, i developed goetl, a highly performant etl pipeline written in go, designed to extract, transform, and load data for rag (retrieval-augmented generation) solutions.
        the tool specializes in processing data from arbitrary file types using flexible configuration options, and leverages go's goroutines to ensure efficient, concurrent data handling.
        goetl provides core functionality such as chunked text splitting, seamless integration with embedding models, and support for multiple database types including redis and postgresql.
        its configurable and scalable nature makes it adaptable to a wide range of file sources and enables hybrid search capabilities in rag systems.

    - title: Developer Platform for Global Telecom Leader
      color: red
      date: Since 2024
      description: |
        Contributed to the development of an internal developer platform for a leading telecom company, built on Backstage.io. 
        The platform streamlined developer workflows, enhancing service discoverability, documentation, and internal tooling. 
        Focus areas included backend development, API integrations, authentication, and CI/CD automation. 
        Ensured scalability and maintainability by leveraging Kubernetes, AWS, and microservices architecture.

      certifications:
        - certName: KCNA Kubernetes and Cloud Native Associate
          company: The Linux Foundation
          date: January 31, 2025
          badge: https://www.credly.com/badges/5e030c4c-4f9f-432f-9754-b92b842eda0c
          description: |
            Earners of this designation demonstrated a basic knowledge of Kubernetes and cloud-native technologies,
            including how to deploy an application using basic kubectl commands, the architecture of Kubernetes (containers, pods, nodes, clusters),
            understanding the cloud-native landscape and projects (storage, networking, GitOps, service mesh),
            and understanding the principles of cloud-native security.

      # misc:
      #   #commandName: newcommand
      #   title: "This Section can have a different command name"
      #   titleColor: teal
      #   content: |
      #     Here the title and the content can have different colors
      #     The content can be multi

      #     line

      #     And spaces       will be respected as well
      #     This section will have the default command: misc
      #     but you can name it something else with the property
      #     commandName: <String>
      #     Give it a shot and try and uncomment the line
      #     commandName: newcommand
      #     now instead of misc you can execute the newcommand for this section
      #     Auto completion will know it too! :D

      #   contentColor: orange
